### ISSUE TITLE
Firmware repository

### ISSUE THREAD

**Issue by Testato** [andreoidb64/uebbi#2]
perche' non ospitare qui i principali firmware per Uebbi ?
Questo al momento sembra essere l'unico Github che parli di Uebbi

**Comment by andreoidb64** [comment]
Ciao Testato,
I firmware originali di uebbi sono attualmente mantenuti qui: http://www.uebproject.org/
e sono accessibili solo agli utenti registrati; copiarli qui senza l'autorizzazione dei mantainer di uebproject, a mio avviso, non sarebbe corretto.
Inoltre, a parte gli script di sistema in bash (non particolarmente significativi), la maggior parte del software presente nel firmware, sono programmi python compilati di cui però non è stato pubblicato il sorgente.
Github invece è nato per condividere il codice/wiki tra sviluppatori; distribuire firmware di questo tipo, senza pubblicarne il codice sorgente, sarebbe un pò come ridurlo ad uno dei tanti siti di filesharing.
Ciao,
Andrea

**Comment by Testato** [comment]
credevo solo il kernel fosse in formato bin.
Ma questi programmi in phyton sono stati scritti da uebproject ?

**Comment by andreoidb64** [comment]
I programmi originali in python, immagino siano stati creati dalla coreana Avantis e successivamente personalizzati dai vari player di telefonia europei che hanno commercializzato webby/uebbi (SFR France, Vodafone DE e Telecom Italia). Vedi http://www.uebproject.org/ per la storia...
Successivamente all'abbandono del prodotto e dei relativi servizi da parte dei suddetti players, dovuti al flop commerciale del progetto, una piccola comunità di sviluppatori tedeschi e italiani, ha ripreso lo sviluppo dei programmi applicativi in python e creato i relativi servizi web indipendenti.
I sorgenti originali in python, non erano stati distribuiti ma, come noto, è possibile ricavarli tramite tool di reverse engineering dai programmi in formato ".pyc" presenti nella flash di uebbi.

**Comment by Testato** [comment]
visto che il reverse engineering non e' reato si potrebbe quindi ricavare e rilasciare qui i sorgenti di tutte le app ?

**Comment by andreoidb64** [comment]
Si potrebbe, certo.
Ma, anche in questo caso, sarebbe più logico che a pubblicare i sorgenti, fossero gli autori di  http://www.uebproject.org/ visto che sono loro i mantainer "ufficiali".

**Comment by Testato** [comment]
non ho ben capito il rapporto fra il sw che si trova in uebbi e uebproject.
perche' dici "ufficiali" ?

Hanno messo mano nell'immagine che comunque gli e' stata data da telecom, cosa che non e' stato un regalo, perche' comunque essendo il uebbi basato su linux avevano comunque obbligo di passare almeno il OS a chi lo richiede.
Volendo rispettare la GPL dovevano dare anche i sorgenti di questa loro Linux Webbi

Sul discorso delle App tirate fuori da uebproject e modificate non so come funziona, forse se comunque in origine la app e' sotto GPL anche il risultato del reverse deve restare sotto GPL ?
Ma nulla vieta partire dall'immagine originale telecom, decompilare e rendere opensource tutto il possibile, e far partire un altro progetto separato da uebproject

**Comment by zoomx** [comment]
Leggendo la discussione su Mikrocontroller c'è un link che portava ai sorgenti ma ormai è morto e non si trova neanche su Archive.org
Anche Avantis sembra morta, il sito c'è ma non c'è alcun indirizzo email funzionante.
La MCU è un po' esotica (AU-1210) ma sul repo di openWRT ce n'è una che appartiene alla stessa famiglia.

Credo che l'attuale atteggiamento di uebproject sia dovuto al fatto che su ebay si trovavano e si trovano ancora dei dispositivi in vendita con il firmware già modificato e la cosa agli autori ha dato molto fastidio.
Comunque solo una parte del firmware in python è stata modificata da uebproject partendo dal firmware tedesco (che non ha il sensore di temperatura e qualche altra cosa).

**Comment by Testato** [comment]
Grazie del riassunto,
Ma comunque chi vuole vendere un uebbi con l'immagine uebproject si registra, la scarica e la installa.
Non c'è nessuna differenza se l'intero progetto viene reso opensource o meno.
A chi fa questi commerci, anzi, poco importa dei sorgenti.

Openwrt è abbastanza utopistico pensare di metterlo, sarebbe bello, ma avere la Webby da poter cross compilare già sarebbe ottimo.
Qualcuno ha detto che scrivendo alla FSF loro potrebbero interfacciarsi, e costringere a far rilasciare i sorgenti di questa Linux Webby :-)

**Comment by andreoidb64** [comment]
@Testato,
Sulla proprietà intellettuale di Webby, francamente, non c'è molta chiarezza e capisco sia facile fare confusione ma:
1) Non mi risulta ci sia stato alcun passaggio ufficiale tra Uebbi Alice di Telecom e Uebproject.
2) Se qualcuno avesse chiesto i sorgenti del OS quando questo era distribuito, avrebbero avuto degli obblighi. Chiederli ora, francamente, mi sembra piuttosto complicato.
3) Non mi risulta che qualcuno sappia quali siano i termini di licenza con cui è stata scritta l'applicazione originale python di Webby e, di conseguenza, anche quelli che l'hanno modificata, non sanno bene come comportarsi riguardo alla licenza.

Riguardo a "decompilare e rendere opensource" centinaia di programmi scritti da altri, senza un loro consenso esplicito, è una cosa che mi lascia perplesso. Personalmente non vorrei che facessero questo a me e, pertanto, eviterei di farlo agli altri.

Fare un fork di uebproject? Si, certo che sarebbe possibile, ma bisognerebbe avere un buon motivo per farlo e trovare persone interessate a mantenerlo/seguirlo, altrimenti a cosa servirebbe?

**Comment by zoomx** [comment]
Oltre ad Avantis e TIM sono coinvolti anche Vodafone per il firmware tedesco e un'altra francese di cui non ricordo il nome (lo vedete al boot) ma che è ancora attiva,i firmware francesi funzionano, i server sono ancora attivi.
Il firmware sul webby è una miscela dei tre firmware con delle modifiche.

L'installazione di openWRT non ce la vedo perché penso che si perderebbe la parte video ma si potrebbe usare la toolchain.
I sorgenti erano sul sito di Avantis ma adesso non ci sono più perché il sito sembra in abbandono o in coma. Si potrebbe chiedere sul forum di Mikrocontroller se qualcuno li ha scaricati ma li non sembra che se ne parli più.

**Comment by Testato** [comment]
buona idea,
c'e' qualche intervento ultimamente dell'utente che ha reversato il protocollo per passare i link delle radio.
Ho scritto un messaggio, vediamo un po'
http://www.mikrocontroller.net/topic/184196?goto=4685579#4685579

**Comment by andreoidb64** [comment]
@zoomx, 
L'azienda francese che distribuiva Webby si chiama SFR France e, come dici tu, ancora eroga i servizi.
Ricordo, qualche mese fa, di aver visto i programmi della TV francese dopo aver installato il firmware "depannage".
In effetti penso che, impostando le opportune configurazioni per la CPU MIPS Alchemy, si potrebbe anche compilare e far funzionare webby con un qualsiasi altro kernel, anche più recente.
Purtroppo, non ho molta esperienza riguardo a questo argomento e perciò non mi sono avventurato su questo tipo di sperimentazione.

@Testato,
Ottima idea! Naturalmente, se trovi qualcosa, sarei ben felice di ospitare qui i sorgenti del kernel in modo che non vadano nuovamente persi.

Se trovo un pò di tempo, vorrei aggiungere una virtualbox appliance "light" con i tool di sviluppo indispensabili per sviluppare su webby (cramfs, yaffs2, binutils, ecc.). Ho già da parte un pò di lavoro fatto partendo da una distribuzione tinycore...

**Comment by Testato** [comment]
i programmi della TV francese ? cioe' col webby si vedono le dirette video ?
Certo se si ritrovano i sorgenti li mettiamo qui

**Comment by andreoidb64** [comment]
Beh insomma, lo schermino 4/3 non é proprio il massimo e per di più c'è
solo qualche canale della TV francese...
