### ISSUE TITLE
Domanda: compilatore Gcc + repo

### ISSUE THREAD

**Issue by Testato** [andreoidb64/uebbi#3]
È già presente o è possibile installare Gcc sul Uebbi ?

L'ultimo firmware uebproject è basato su debian ? Contiene un repo preconfigurato da dove poi scaricare nuove app ed aggiornamenti ?

**Comment by andreoidb64** [comment]
gcc non è presente nel sistema.
Le risorse hardware di Webby sono piuttosto limitate e credo che sarebbe complicato farci stare un tool del genere.
L'hardware, per intenderci, è paragonabile a quello di un modem di casa o roba simile; in questo tipo di dispositivi non sono presenti i pacchetti normalmente distribuiti sui PC e la maggior parte dei programmi sono disponibili nella busybox.

Volendo compilare nuovi file eseguibili per ARM, immagino sia più semplice ricorrere a tool di cross-compiling da altre piattaforme.
Anche se qualcuno, in passato, ha fatto qualche emulazione di distribuzione debian per webby (vedi http://santi.smbit.it/tools/debian-webby-debby/) non mi risulta che esistano progetti attivi o repository in formato deb.
Il sorgenti del kernel poi non sono disponibili (io almeno non sono riuscito a trovarli) e il kernel attuale resta quello che si legge da # uname -a
_Linux webby 2.6.24 #498 Wed May 20 14:11:38 KST 2009 mips GNU/Linux_

**Comment by Testato** [comment]
avevo trovato quel link, cosa intendi per Emulazione di Distribuzione ?
non ho ben capito cosa lui abbia fatto.

In openwrt (classico OS per modem) c'e' gcc, ma capisco che sara' stato un bel lavoraccio farcelo stare.

Non ci sono esempi in giro di cross-compilation ?

**Comment by andreoidb64** [comment]
Intendo dire che, secondo me, non è mai esistita una distribuzione Debian per Webby, ma solo qualcuno che ha copiato un pò di script da una distribuzione Debian nella /etc di Webbi per farcelo somigliare...

Sul cross-compiling non so dirti molto, non sono un esperto su questo argomento.
