### ISSUE TITLE
Esiste un modo di eseguire il player da command line?

### ISSUE THREAD

**Issue by provenza** [andreoidb64/uebbi#4]
Ciao,
sono un utilizzatore di uebbi. Volevo chiederti una cosa. Esiste un modo per lanciare le funzionalità del uebbi da command line? ho visto che la distro disponibile non consente di fare un granchè. grazie

**Comment by andreoidb64** [comment]
Ciao Provenza,
In linea di principio su un sistema *nix quasi tutto può essere avviato da linea di comando.
Riguardo alla domanda specifica (avviare il le funzioni di player di uebbi da linea di comando) che io sappia questa funzione non è documentata.
Puoi provare a fare un po di reverse engineering analizzando i processi di sistema quando il player viene eseguito e, una volta identificato il PID relativo al processo del player, rilevare le opzioni e variabili in uso dalla directory /proc/#PID.
Non è detto però che sia poi effettivamente possibile eseguire il processo al di fuori dell'ambiente di esecuzione Python di uebbi...
In alternativa, se i formati da riprodurre sono compatibili, potresti usare "sox" che appunto funziona da riga di comando.
Qualche mese fa ne ho compilato una versione per uebbi che trovi in https://github.com/andreoidb64/uebbi
Ciao,
Andrea
